site_name: AudioKit Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - toc.integrate

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true

nav:
  - Home: index.md
  - API Reference:
    - Core: api/core.md
    - AI: api/ai.md
    - CLI: api/cli.md 