[tool.poetry]
name = "audiokit"
version = "0.2.0"
description = "AudioKit SDK for AI-driven audio processing."
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
torch = "^2.0"
torchaudio = "^2.0"
onnxruntime = "^1.15"
numpy = "^1.24"
typer = "^0.9.0"

[tool.poetry.scripts]
ak = "audiokit.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
pytest-cov = "^4.0"
soundfile = "^0.12"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=audiokit --cov-report=term-missing"
