[tool.poetry]
name = "audiokit"
version = "0.1.0"
description = "Client library for audio analysis"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.24.0"
typer = "^0.9.0"
rich = "^13.6.0"
pyyaml = "^6.0.1"
pydantic = "^2.6.0"
librosa = "0.10.0"
audiokit-core = {path = "../audiokit-core", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
ruff = "^0.1.0"

[tool.poetry.scripts]
audiokit = "audiokit.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88target-version = "py311"
