[tool.poetry]
name = "audiokit"
version = "0.1.0"
description = "Client library for audio analysis"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.3"
requests = "^2.27.1"
demucs = "^3.0.5"
audiokit-core = {path = "../audiokit-core", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
ruff = "^0.1.0"

[tool.poetry.scripts]
audiokit = "audiokit.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88target-version = "py311"
