import pytest
import os

# This fixture automatically changes the working directory for each test.
# Any output files (e.g. .wav files) generated by the tested code using relative paths
# will be created in a temporary directory instead of in the project root.
@pytest.fixture(autouse=True)
def change_to_temp_dir(tmp_path, monkeypatch):
    # Optionally, you can create a subdirectory (e.g., "generated_audio") inside tmp_path:
    generated_dir = tmp_path / "generated_audio"
    generated_dir.mkdir()
    monkeypatch.chdir(generated_dir)
    # Debug: print the current working directory (remove or comment in production)
    print("Current working directory changed to:", os.getcwd()) 